### ISSUE TITLE
A question to max sigma

### ISSUE THREAD

**Issue by pbizimis** [AlexiaJM/AdversarialConsistentScoreMatching#2]
Hey,
thanks a lot for your code and [your help](https://github.com/yang-song/score_sde/issues/2).

I used your code to find the approximate max sigma value for my dataset. My result is a value of 217. This seems rather high. My dataset contains 31.000 images; each is a screenshot of a website with a resolution of 128x128.
Should I just work with that value or is there something I should/can do?

Thanks

**Comment by AlexiaJM** [comment]
Hi @pbizimis,

This seems totally normal, your dataset must have more variety than Churches (https://github.com/AlexiaJM/AdversarialConsistentScoreMatching/blob/master/configs/church.yml). There's no issue with starting with a high sigma except a few more iterations when sampling. Anything around 200 should be good for you.

Alexia

**Comment by pbizimis** [comment]
Awesome, thanks
