### ISSUE TITLE
How to use the DDPM score net architecture in this code?

### ISSUE THREAD

**Issue by zqOuO** [AlexiaJM/AdversarialConsistentScoreMatching#4]
Hi Alexia! Thanks a lot for your excellent code.
I've been working on this lately. I found the score net of NCSN can be directly used and works fine, but how to train a score net like DDPM and use the consistent sampling? Would you please provide a link to your pre-trained score networks about this architecture?
Thank you!

**Comment by AlexiaJM** [comment]
Hi,

Here is one way: In DDPM or DDIM, one part of the algorithm first estimate x(0) given x(t) and then it clips x(0) to the correct range. See https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/models/__init__.py#L289 for example. Only after that, it brings x(0) back to x(t-1). What you could do instead is to take the estimated x(0) (which is just the EDS called H in our paper), and apply directly the CAS algorithm (second line with the '\beta') from proposition 3.

The pretrained score networks are in the README, but there is no DDPM one. Theres a few PyTorch githubs with DDPM: https://github.com/w86763777/pytorch-ddpm, https://github.com/lucidrains/denoising-diffusion-pytorch.

Alexia

**Comment by zqOuO** [comment]
Thank you a lot!

**Comment by AlexiaJM** [comment]
No problem, I hope it works out!

**Comment by zqOuO** [comment]
Hi AlexiaJM, if we use the estimated x_0 in DDPM to replace the H(x) in your proposition 3, how to establish a step size schedule for DDPM? Thus DDPM has different noise schedule from NCSN, we can not use the annealed step size = sigma_i/sigma_N **2 like NCSN. or can you provide me the code you used in DDPM part of your excellent paper? Thank you!
