### ISSUE TITLE
DDPM score-net architecture

### ISSUE THREAD

**Issue by zqOuO** [AlexiaJM/AdversarialConsistentScoreMatching#5]
Hi AlexiaJM, thank you for your code!
if we use the estimated x_0 in DDPM to replace the H(x) in your proposition 3, how to establish a step size schedule for DDPM? Thus DDPM has a different noise schedule from NCSN, we can not use the annealed step size = (sigma_i/sigma_N) **2 like NCSN (in NCSN we perturb data by x_t = x_0 + sigma_t * z and DDPM uses x_t = alpha_t * x_0 + (1 - alpha_t) * z). Or can you provide me the code you used in DDPM part of your excellent paper? I am trying to use your code as a baseline for DDIM, and I want to use your consistent sampling in DDPM architecture. Thank you!

**Comment by AlexiaJM** [comment]
Hi @ziqwnudt, 

This is a non-trivial problem, I am not sure how to do it. You can try to look at DDPM code or the math behind the Consistent Annealed Sampling in order to figure out a solution.  But, alas I cannot help 😔.

**Comment by zqOuO** [comment]
@AlexiaJM Hi, thank you for your reply!  I thought this is non-trivial too. I found you have some experiment results obtained from DDPM, maybe there's something wrong with my understanding. I know DDPM first estimates x_0 from a given x_t, then it uses this estimated x_0 to obtain x_t-1, so I can use this estimated x_0 in your proposition3 and perform consistent sampling. The estimated x_0 is denoised_x in your code, but if I directly use the denoised_x to run consistent sampling with proposition3, will I get the same result  as directly perform a consistent sampling? Since the proposition 3 is equivalent with the Algorithm 2 in your paper. Indeed, you obtain better FID with DDPM compared with NCSN. Can you provide me the code that you obtain these results? Wish you a nice day!

**Comment by AlexiaJM** [comment]
Hi @ziqwnudt , I did not use DDPM in this paper, but I used the unet architecture, is this what you mean?
See https://github.com/AlexiaJM/AdversarialConsistentScoreMatching/blob/master/tests/training_sampling_fid.sh#L248.

**Comment by zqOuO** [comment]
@AlexiaJM Sorry, I think there must be something wrong with my understanding. What is the meaning of unet？Is this architecture similar to DDPM?
